name: Publish to npm
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[publish]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: ArnaudBarre/npm-publish@v1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
